### ISSUE TITLE
How to specify "packages-above-depth" in yaml file?

### ISSUE THREAD

**Issue by roncapat** [colcon/colcon-defaults#39]
I tried:

```yaml
  "packages-above-depth": {1, ["emrs_test"]}
  "packages-above-depth": [1, ["emrs_test"]]
  "packages-above-depth": {1, "emrs_test"}
  "packages-above-depth": [1, "emrs_test"]
```
but I can't figure out the correct format for such parameter... May I ask for advice?
